### ISSUE TITLE
Use zetcd instead of jetcd

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/apache-kafka-on-k8s#9]
Does it makes sense to use zetcd instead of etcd as that would reduce the amount of changes to make this project work?

https://github.com/etcd-io/zetcd

**Comment by baluchicken** [comment]
Hi @raoofm, AFAIK you can use zetcd with vanilla Kafka. Zetcd is a proxy between Zookeeper and Etcd. Kafka thinks it still speaks with Zookeeper but instead zetcd . With this specific Kafka version you cannot use Zetcd because we made changes inside Kafka to use Etcd directly using the Jetcd project.

**Comment by raoofm** [comment]
@baluchicken yes kafka thinks it is talking to zookeeper but actual data goes in etcd - if zetcd is used. I think as you suggested, this repo moved a lot forward and changed the actual kafka code which I was thinking was not necessary and zetcd could simplify the switch from zookeeper to etcd backend.

**Comment by raoofm** [comment]
this can be closed.
